package gestionhotelera.persistence;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Gestor de conexion JDBC e inicializador de esquema para PostgreSQL.
 * La configuracion se puede indicar con DB_URL, DB_USER y DB_PASSWORD.
 */
public class Database {
    private static final String DEFAULT_URL = "jdbc:postgresql://localhost:5432/hotel_db";
    private static final String DEFAULT_USER = "hotel_user";
    private static final String DEFAULT_PASSWORD = "hotel_password";

    private final String url;
    private final String user;
    private final String password;

    public Database() {
        this(configValue("hotel.db.url", "DB_URL", DEFAULT_URL),
                configValue("hotel.db.user", "DB_USER", DEFAULT_USER),
                configValue("hotel.db.password", "DB_PASSWORD", DEFAULT_PASSWORD));
    }

    public Database(String url) {
        this(url,
                configValue("hotel.db.user", "DB_USER", DEFAULT_USER),
                configValue("hotel.db.password", "DB_PASSWORD", DEFAULT_PASSWORD));
    }

    public Database(String url, String user, String password) {
        this.url = url;
        this.user = user;
        this.password = password;
    }

    public static Database fromEnvironment() {
        return new Database();
    }

    public Connection getConnection() throws SQLException {
        return DriverManager.getConnection(url, user, password);
    }

    /**
     * Crea las tablas necesarias si no existen.
     * El mismo esquema esta documentado en docs/schema.sql y se carga al iniciar Docker.
     */
    public void initializeSchema() throws SQLException {
        try (Connection c = getConnection(); Statement s = c.createStatement()) {
            s.execute("CREATE TABLE IF NOT EXISTS habitaciones ("
                    + "numero INT PRIMARY KEY,"
                    + "capacidad INTEGER NOT NULL,"
                    + "precio_base NUMERIC(12, 2) NOT NULL,"
                    + "tipo VARCHAR(30) NOT NULL,"
                    + "estado VARCHAR(30) NOT NULL,"
                    + "CONSTRAINT habitaciones_capacidad_chk CHECK (capacidad > 0),"
                    + "CONSTRAINT habitaciones_precio_chk CHECK (precio_base >= 0)"
                    + ")");

            s.execute("CREATE TABLE IF NOT EXISTS huespedes ("
                    + "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "nombre VARCHAR(100) NOT NULL,"
                    + "apellido VARCHAR(100) NOT NULL,"
                    + "dni VARCHAR(32) NOT NULL UNIQUE,"
                    + "telefono VARCHAR(40),"
                    + "email VARCHAR(160),"
                    + "tipo VARCHAR(60)"
                    + ")");

            s.execute("CREATE TABLE IF NOT EXISTS reservas ("
                    + "codigo VARCHAR(40) PRIMARY KEY,"
                    + "huesped_id INTEGER NOT NULL,"
                    + "habitacion_num INTEGER NOT NULL,"
                    + "fecha_ingreso DATE NOT NULL,"
                    + "fecha_egreso DATE NOT NULL,"
                    + "estado VARCHAR(30) NOT NULL,"
                    + "CONSTRAINT reservas_fechas_chk CHECK (fecha_egreso > fecha_ingreso),"
                    + "FOREIGN KEY(huesped_id) REFERENCES huespedes(id) ON DELETE CASCADE,"
                    + "FOREIGN KEY(habitacion_num) REFERENCES habitaciones(numero) ON DELETE RESTRICT"
                    + ")");

            s.execute("CREATE TABLE IF NOT EXISTS estadias ("
                    + "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "reserva_codigo VARCHAR(40) NOT NULL UNIQUE,"
                    + "fecha_ingreso_real DATE NOT NULL,"
                    + "fecha_egreso_real DATE NOT NULL,"
                    + "CONSTRAINT estadias_fechas_chk CHECK (fecha_egreso_real >= fecha_ingreso_real),"
                    + "FOREIGN KEY(reserva_codigo) REFERENCES reservas(codigo) ON DELETE CASCADE"
                    + ")");

            s.execute("CREATE TABLE IF NOT EXISTS servicios ("
                    + "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "estadia_id INTEGER NOT NULL,"
                    + "nombre VARCHAR(120) NOT NULL,"
                    + "descripcion TEXT,"
                    + "precio NUMERIC(12, 2) NOT NULL,"
                    + "CONSTRAINT servicios_precio_chk CHECK (precio >= 0),"
                    + "FOREIGN KEY(estadia_id) REFERENCES estadias(id) ON DELETE CASCADE"
                    + ")");

            s.execute("CREATE TABLE IF NOT EXISTS pagos ("
                    + "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "estadia_id INTEGER NOT NULL,"
                    + "monto NUMERIC(12, 2) NOT NULL,"
                    + "fecha TIMESTAMP NOT NULL,"
                    + "metodo VARCHAR(80) NOT NULL,"
                    + "estado VARCHAR(30) NOT NULL,"
                    + "CONSTRAINT pagos_monto_chk CHECK (monto >= 0),"
                    + "FOREIGN KEY(estadia_id) REFERENCES estadias(id) ON DELETE CASCADE"
                    + ")");

            s.execute("CREATE INDEX IF NOT EXISTS idx_reservas_habitacion_fechas "
                    + "ON reservas(habitacion_num, fecha_ingreso, fecha_egreso)");
            s.execute("CREATE INDEX IF NOT EXISTS idx_servicios_estadia ON servicios(estadia_id)");
            s.execute("CREATE INDEX IF NOT EXISTS idx_pagos_estadia ON pagos(estadia_id)");
        }
    }

    private static String configValue(String propertyName, String envName, String defaultValue) {
        String propertyValue = System.getProperty(propertyName);
        if (propertyValue != null && !propertyValue.isBlank()) {
            return propertyValue;
        }
        String envValue = System.getenv(envName);
        if (envValue != null && !envValue.isBlank()) {
            return envValue;
        }
        return defaultValue;
    }
}
