-- Esquema PostgreSQL para el sistema de gestion hotelera.
-- Este archivo se monta en Docker como /docker-entrypoint-initdb.d/01_schema.sql.

CREATE TABLE IF NOT EXISTS habitaciones (
  numero INT PRIMARY KEY,
  capacidad INTEGER NOT NULL,
  precio_base NUMERIC(12, 2) NOT NULL,
  tipo VARCHAR(30) NOT NULL,
  estado VARCHAR(30) NOT NULL,
  CONSTRAINT habitaciones_capacidad_chk CHECK (capacidad > 0),
  CONSTRAINT habitaciones_precio_chk CHECK (precio_base >= 0)
);

CREATE TABLE IF NOT EXISTS huespedes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  apellido VARCHAR(100) NOT NULL,
  dni VARCHAR(32) NOT NULL UNIQUE,
  telefono VARCHAR(40),
  email VARCHAR(160),
  tipo VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS reservas (
  codigo VARCHAR(40) PRIMARY KEY,
  huesped_id INTEGER NOT NULL,
  habitacion_num INTEGER NOT NULL,
  fecha_ingreso DATE NOT NULL,
  fecha_egreso DATE NOT NULL,
  estado VARCHAR(30) NOT NULL,
  CONSTRAINT reservas_fechas_chk CHECK (fecha_egreso > fecha_ingreso),
  CONSTRAINT reservas_huesped_fk
    FOREIGN KEY (huesped_id) REFERENCES huespedes(id) ON DELETE CASCADE,
  CONSTRAINT reservas_habitacion_fk
    FOREIGN KEY (habitacion_num) REFERENCES habitaciones(numero) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS estadias (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_codigo VARCHAR(40) NOT NULL UNIQUE,
  fecha_ingreso_real DATE NOT NULL,
  fecha_egreso_real DATE NOT NULL,
  CONSTRAINT estadias_fechas_chk CHECK (fecha_egreso_real >= fecha_ingreso_real),
  CONSTRAINT estadias_reserva_fk
    FOREIGN KEY (reserva_codigo) REFERENCES reservas(codigo) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS servicios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estadia_id INTEGER NOT NULL,
  nombre VARCHAR(120) NOT NULL,
  descripcion TEXT,
  precio NUMERIC(12, 2) NOT NULL,
  CONSTRAINT servicios_precio_chk CHECK (precio >= 0),
  CONSTRAINT servicios_estadia_fk
    FOREIGN KEY (estadia_id) REFERENCES estadias(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pagos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estadia_id INTEGER NOT NULL,
  monto NUMERIC(12, 2) NOT NULL,
  fecha TIMESTAMP NOT NULL,
  metodo VARCHAR(80) NOT NULL,
  estado VARCHAR(30) NOT NULL,
  CONSTRAINT pagos_monto_chk CHECK (monto >= 0),
  CONSTRAINT pagos_estadia_fk
    FOREIGN KEY (estadia_id) REFERENCES estadias(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_reservas_habitacion_fechas
  ON reservas(habitacion_num, fecha_ingreso, fecha_egreso);

CREATE INDEX IF NOT EXISTS idx_servicios_estadia
  ON servicios(estadia_id);

CREATE INDEX IF NOT EXISTS idx_pagos_estadia
  ON pagos(estadia_id);
